### ISSUE TITLE
Adapt to magit/git-commit v2.1.0

### ISSUE THREAD

**Issue by tarsius** [yasuyk/git-commit-training-wheels-mode#1]
Magit v2.1.0 has just been released. `git-commit-mode.el` is no part of the Magit package, under the new name `git-commit.el`. It is distributed as a separate Elpa package.

You should either switch to extend that new package, or drop the training wheels completely.

The new `git-commit` can be configured to look out the window all day long too. It won't call the police like this package does, but it yells at the kids.

To make `git-commit` complain more add something to `git-commit-finish-query-functions`.

Re https://github.com/milkypostman/melpa/issues/2894.

**Comment by yasuyk** [comment]
@tarsius Sorry for the very very delayed response, and Thank you for telling me. I will drop this package later.
